name: PHPUnit Tests for Laravel Boilerplate

on:
  push:
    branches:
      - master
      - feature/*
  pull_request:
    branches:
      - master

jobs:
  phpunit-tests-for-laravel-boilerplate:
    name: PHPUnit Tests for Laravel Boilerplate - PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: ['7.4'] # matching latest Laravel version

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # optional step - watch this step for successful extensions installed, based on OS list defined.
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo, curl, xml, libxml, zip, pcntl, json, tokenizer, pdo, pgsql, sqlite, pdo_sqlite, sqlsrv, pdo_sqlsrv, mysql # optional
          ini-values: "post_max_size=256M" # optional

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p .github
          touch .github/database.sqlite

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: .github/database.sqlite
        run: vendor/bin/phpunit
