name: Run composer update and create pull request

on:
  schedule:
    # Define your cron schedule below, UTC
    - cron: '0 0 * * fri'

jobs:
  run_composer_update_and_create_pull_request:
    name: Run composer update and create pull request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: composer update action
        uses: kawax/composer-update-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
