name: Example - PHP versions with selected modules / extensions, on supported operating systems

on:
  push:
    branches:
      - master
      - release/*

jobs:
  php-versions-with-selected-modules-on-supported-os:
    name: PHP ${{ matrix.php-versions }} test on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: ['7.2', '7.3', '7.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo # optional
          ini-values: "post_max_size=256M" # optional

      - name: Check PHP version
        run: php -v

      - name: Check PHP modules installed (Extensions)
        run: php -m
